# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Set the Python version and install requirements
build:
  os: ubuntu-24.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      - pip install -r docs/requirements.txt
      - pip install -e .[docs]

# Optionally build docs in additional formats such as PDF
formats: all

# Optionally set the version of Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally enable PDF/Epub builds
build:
  os: ubuntu-24.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      - pip install -r docs/requirements.txt

# Optionally include or exclude patterns
# build:
#   file: docs/conf.py
#   include_paths:
#     - docs/
#     - src/
#   exclude_patterns:
#     - .venv/
#     - build/
#     - dist/
#     - tests/

# Optionally set the default branch
defaults:
  version: develop

# Optionally hide build date
html_theme_options:
  display_version: true
  style_external_links: true
