name: Publish Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: false

env:
  PYTHON_VERSION: '3.8'

jobs:
  deploy:
    name: Build and Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
    
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
    
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
    
      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir dist/
    
      - name: Verify package
        run: |
          twine check dist/*
    
      - name: Publish to PyPI
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
    
      - name: Show package info
        run: |
          echo "Package built for version: ${{ github.event.release.tag_name }}"
          ls -la dist/
