name: Publish Python Package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Matches 1.0.0, 2.3.4, etc. (without v prefix)
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: false

env:
  PYTHON_VERSION: '3.9'

jobs:
  deploy:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for PyPI Trusted Publisher OIDC
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
    
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
    
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
    
      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir dist/
    
      - name: Verify package
        run: |
          twine check dist/*
    
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            skip-existing: true
            verbose: true
            print-hash: true
    
      - name: Show package info
        run: |
          echo "Package built for version: ${{ github.event.release.tag_name }}"
          ls -la dist/
