name: Validate

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.rst'
      - '**.gitignore'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.rst'
      - '**.gitignore'
      - '.github/**'

env:
  PYTHON_VERSION: '3.8'

jobs:
  test:
    name: Test Python 3.8 on Ubuntu
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    
    strategy:
      fail-fast: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      
      - name: Set up environment and install dependencies
        run: |
          # Create virtual environment
          python -m venv .venv
          
          # Activate and set up the environment
          source .venv/bin/activate
          
          # Ensure pip is up to date and install build tools
          python -m pip install --upgrade pip setuptools wheel build
          
          # Install package with dev dependencies from pyproject.toml
          pip install -e ".[dev]"
          
      - name: Build package
        run: |
          source .venv/bin/activate
          python -m build --sdist --wheel --outdir dist/ .
      
      - name: Check code style
        run: |
          source .venv/bin/activate
          black --check .
          flake8 .
          isort --check-only .
          mypy .
