name: validate
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - '**.rst'
    tags-ignore:
    - v*
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - '**.rst'
  
jobs:
  test_nucleo:
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        id: run-tox
        run: tox -vv
        env:
          PLATFORM: ${{ matrix.platform }}
